; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc1-n16r8]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino
monitor_speed = 115200
board_upload.speed = 921600

board_build.arduino.memory_type = qio_opi
build_flags = 
    -DBOARD_HAS_PSRAM
board_upload.flash_size = 16MB


; Point to your local Arduino libraries folder
lib_deps =
    Fiooodooor/HLK-LD245X @ ^0.9.5
    mathworks/ThingSpeak @ ^2.1.1
    adafruit/Adafruit SHT4x Library @ ^1.0.5
    adafruit/Adafruit BusIO @ ^1.17.4

